name: lociPARSE
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10.4
  - numpy-base=1.22.3
  - tqdm=4.64.0
  - pytorch=1.12.0
  - scipy=1.7.3
  - scikit-learn=1.1.1
  - pandas=1.4.4
  - openpyxl
  - seaborn=0.12.0
  - matplotlib=3.5.2
